name: Publish libraries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest  
    env:
      Solution_Name: Samsung.SmartTv.Client.sln                         

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Pack client abstractions
      run: dotnet pack src\libs\Samsung.SmartTv.Client\Samsung.SmartTv.Client.csproj -c Release
    
    - name: Pack web sockes client
      run: dotnet pack src\libs\Samsung.SmartTv.Client.WebSockets\Samsung.SmartTv.Client.WebSockets.csproj -c Release
    
    - name: Publish to NuGet.org
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
